
include: package:very_good_analysis/analysis_options.7.0.0.yaml
linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint
  