name: to_win
description: "Super awesome template for Comrades Flutter projects by Sharafuddin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

# Actualy Flutter SDK version is 3.27.0
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_remote_config: ^5.3.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.2
  upgrader: ^11.3.1
  shared_preferences: ^2.3.5
  very_good_analysis: ^7.0.0
  flutter_svg: ^2.0.17
  firebase_crashlytics: ^4.3.0
  intl: ^0.19.0
  package_info_plus: ^8.1.3
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.2
  auto_route: ^9.3.0+1
  drift: ^2.24.0
  drift_flutter: ^0.2.4
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.3.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_gen_runner: 
  freezed: ^2.5.8
  json_serializable: ^6.9.2
  drift_dev: ^2.24.0

dependency_overrides:
  # The latest version of FlutterGen if 5.8.0
  # check new version at https://pub.dev/packages/flutter_gen
  # and update it in pubspec.yaml
  # for work with freezed: ^2.5.8
  flutter_gen_core:
    git:
      url: https://github.com/FlutterGen/flutter_gen.git
      path: packages/core/

flutter:

  generate: true

  uses-material-design: true

  assets:
    - assets/logo.png