// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbxbYHu_LGF-2zdncVY5o0NgAUbQDcKdI',
    appId: '1:1088954034562:web:435dcbd1f3bc9fd194c79b',
    messagingSenderId: '1088954034562',
    projectId: 'cmd-template',
    authDomain: 'cmd-template.firebaseapp.com',
    storageBucket: 'cmd-template.firebasestorage.app',
    measurementId: 'G-DQMHN9XLDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCguZqDRGSit8XSX2UbLv6thWZuF75IzgE',
    appId: '1:1088954034562:android:704c1dff25e7868094c79b',
    messagingSenderId: '1088954034562',
    projectId: 'cmd-template',
    storageBucket: 'cmd-template.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeBRo082gyakVan1DCR4SRKO3NhU5ge44',
    appId: '1:1088954034562:ios:ff708fce858d44b894c79b',
    messagingSenderId: '1088954034562',
    projectId: 'cmd-template',
    storageBucket: 'cmd-template.firebasestorage.app',
    iosBundleId: 'com.becandier.towin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeBRo082gyakVan1DCR4SRKO3NhU5ge44',
    appId: '1:1088954034562:ios:ff708fce858d44b894c79b',
    messagingSenderId: '1088954034562',
    projectId: 'cmd-template',
    storageBucket: 'cmd-template.firebasestorage.app',
    iosBundleId: 'com.becandier.towin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbxbYHu_LGF-2zdncVY5o0NgAUbQDcKdI',
    appId: '1:1088954034562:web:a29fc920db5977a294c79b',
    messagingSenderId: '1088954034562',
    projectId: 'cmd-template',
    authDomain: 'cmd-template.firebaseapp.com',
    storageBucket: 'cmd-template.firebasestorage.app',
    measurementId: 'G-WZSPC73DLF',
  );
}
